/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;
import juego.*;


/**
 *
 * @author PC_BASMA
 */
public class VentanaPrincipal extends javax.swing.JFrame {
private Juego juego;
private JuegoController controller;

private PanelZombi panelZombi;
private PanelAccionesZombi panelAcciones;
private PanelControl panelControl;
private LogPanel logPanel;
private TableroGUI tableroGUI;


    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
   public VentanaPrincipal() {
    initComponents();
    inicializarJuego();
}

   private void inicializarJuego() {

    // 1. Layout principal
    getContentPane().setLayout(new java.awt.BorderLayout());

    // 2. Crear juego y controller
    juego = new Juego(1); // 1 zombi por ahora
    controller = new JuegoController(juego);

    // 3. Crear paneles
    panelZombi = new PanelZombi();
    panelAcciones = new PanelAccionesZombi(controller);
    panelControl = new PanelControl(controller);
    logPanel = new LogPanel();
    tableroGUI = new TableroGUI(juego.getTablero());


    // 4. Conectar controller con paneles
    controller.setPanelZombi(panelZombi);
    controller.setLogPanel(logPanel);

    // 5. Añadir paneles a la ventana
    add(panelControl, java.awt.BorderLayout.NORTH);
    add(panelAcciones, java.awt.BorderLayout.WEST);
    add(panelZombi, java.awt.BorderLayout.EAST);
    add(logPanel, java.awt.BorderLayout.SOUTH);
    add(tableroGUI, java.awt.BorderLayout.CENTER);


    // 6. Primer refresco
    controller.actualizarPanelZombi();

    revalidate();
    repaint();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
